# Generated by Django 5.2.10 on 2026-01-09 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='otp_type',
            field=models.CharField(choices=[('registration', 'Registration'), ('password_reset', 'Password Reset')], max_length=20),
        ),
    ]
